### ISSUE TITLE
Error Code Short Link Not Working

### ISSUE THREAD

**Issue by nerddtvg** [dotnet/EntityFramework.ApiDocs#121]
https://github.com/dotnet/efcore/blob/afc2f0bca33ca312de58084e040518c62dc22383/src/EFCore.SqlServer/Properties/SqlServerStrings.Designer.cs#L215

`https://aka.ms/efcore-docs-sqlserver-save-changes-and-computed-columns` redirects to bing.com rather than the documentation.

The same for: https://github.com/dotnet/efcore/blob/b906ca3dd58dc89952960261e7d6eea766d4a7b4/src/EFCore.SqlServer/Properties/SqlServerStrings.resx#L291

**Comment by roji** [comment]
Duplicate of §4129
