### ISSUE TITLE
Incorrect documentation generated for methods which changed return type

### ISSUE THREAD

**Issue by smitpatel** [dotnet/EntityFramework.ApiDocs#73]
EF Core has API over `DbSet<T>` - `AddAsync` which returned task in past. In 3.0 release, we changed it to return ValueTask instead.

Generated xml content does not contain the change.
https://github.com/dotnet/EntityFramework.ApiDocs/blob/796ac2bde94aef7b99de81820b22657ce0f3c14b/dotnet/xml/Microsoft.EntityFrameworkCore/DbSet%601.xml#L152-L170

XML mentions about API returning Task. Also assemblies specified does not include 3.x onward.
So for 3.x we did not generate API in xml for this method.

At the same time,
On doc page, https://docs.microsoft.com/en-us/dotnet/api/microsoft.entityframeworkcore.dbset-1.addasync?view=efcore-3.1#applies-to

It says that it is applicable to 3.0 & 3.1. Not sure why it computed that.

It seems that this is issue somewhere in reference doc generation.

cc: @scottaddie

**Comment by scottaddie** [comment]
@mimisasouvanh Is this something your team can investigate?

**Comment by mimisasouvanh** [comment]
@scottaddie We've a backlog item to support versioning for return types - which is starting work in Q4 or Q1.

**Comment by mimisasouvanh** [comment]
@smitpatel We've implemented a feature to fix this issue. Please verify and close. Thank you!
